useGroupedVersion: true

version_info_list_js:
  - value: latest version(11.0.3000)
  - value: 10.x
    child:
      - 10.5.3000
      - 10.4.3100
      - 10.4.2002
      - 10.2.1000
      - 10.0.21
      - 10.0.20
  - value: 9.x
    child:
      - 9.6.42
      - 9.6.40
      - 9.6.33
      - 9.6.32
      - 9.6.31
      - 9.6.30
      - 9.6.21
      - 9.6.20
      - 9.6.11
      - 9.6.10
      - 9.6.2
      - 9.6.1
      - 9.6.0
      - 9.3.1
      - 9.3.0
      - 9.2.13
      - 9.2.12
      - 9.2.11
      - 9.0.2
      - 9.0.1
      - 9.0.0
  - value: 8.x
    child:
      - 8.8.7
      - 8.8.5
      - 8.8.3
      - 8.8.0
      - 8.6.3
      - 8.6.0
      - 8.4.0
      - 8.2.5
      - 8.2.3
      - 8.2.1
      - 8.2.0
      - 8.1.3
      - 8.1.2
      - 8.1.0
      - 8.0.0
  - value: 7.x
    child:
      - 7.6.0
      - 7.5.0
